'use strict';
const $=s=>document.querySelector(s),categories=['AI & Frontier','Monetary Architecture','Macroeconomics','Energy & Physics','Infrastructure','Distributed Systems'];
const published=(window.PUBLISHED||[]).map(e=>({...e,tags:[e.kind,...e.nodes]}));
let local=[];try{local=JSON.parse(localStorage.getItem('eli5-drafts')||'[]').filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.html==='string'&&categories.includes(x.category));}catch{}local.forEach(e=>{e.subcategory??='Your drafts';e.date??=''});let catalog=[...published,...local],category='All',active=null,lastFocus=null,toastTimer;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function diagram(e){if(e.card)return e.card;const c=e.color||'#ff8059',n=e.nodes||['IDEA','MODEL','INSIGHT'];const inner=n.map((x,i)=>`<rect x="${19+i*103}" y="50" width="76" height="51" rx="5" fill="#20271b" stroke="${c}" stroke-opacity=".7"/><text x="${57+i*103}" y="79" fill="${c}">${esc(x)}</text>`).join('')+`<path d="M96 75h25m-5-4 5 4-5 4M199 75h25m-5-4 5 4-5 4" stroke="${c}" fill="none"/><path d="M263 105v18H57v-18" stroke="${c}" stroke-dasharray="3 4" opacity=".4" fill="none"/>`;return `<svg class="dg" style="--dc:${c}" viewBox="0 0 320 155" role="img" aria-label="${esc(e.title)} schematic">${inner}</svg>`;}
const newest=(a,b)=>(b.date||'').localeCompare(a.date||'');
const fmtDate=d=>{if(!d)return 'Draft';const [y,m,day]=d.split('-');return `${+day} ${'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ')[m-1]} ${y}`;};
function filtered(){let q=$('#search').value.trim().toLowerCase();let list=catalog.filter(e=>(category==='All'||e.category===category)&&[e.title,e.category,e.subcategory,e.summary,...(e.tags||[])].join(' ').toLowerCase().includes(q));const by={newest,short:(a,b)=>a.minutes-b.minutes,long:(a,b)=>b.minutes-a.minutes,alpha:(a,b)=>a.title.localeCompare(b.title)}[$('#sort').value]||newest;return list.sort((a,b)=>categories.indexOf(a.category)-categories.indexOf(b.category)||a.subcategory.localeCompare(b.subcategory)||by(a,b));}
function card(e){return `<article class="card" style="--card-color:${e.color||'#ff8059'}"><div class="card-top"><div class="card-meta"><span class="index">${esc(fmtDate(e.date).toUpperCase())}</span><span>${esc(e.category.toUpperCase())}</span><span class="time">${e.minutes} MIN ↗</span></div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="diagram">${diagram(e)}</div></div><ul>${e.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><div class="card-actions"><button data-read="${esc(e.id)}">Read essay <span>↗</span></button><button class="icon" data-share="${esc(e.id)}" aria-label="Copy share link for ${esc(e.title)}">⧉</button><a class="icon" href="${link(e.id,true)}" target="_blank" rel="noopener" aria-label="Open ${esc(e.title)} in new window">↗</a></div></article>`;}
function row(e){return `<article class="row"><time datetime="${esc(e.date)}">${esc(fmtDate(e.date))}</time><div><button class="row-title" data-read="${esc(e.id)}">${esc(e.title)}</button><p>${esc(e.summary)}</p></div><span class="row-time">${e.minutes} MIN</span><a class="icon" href="${link(e.id,true)}" target="_blank" rel="noopener" aria-label="Open ${esc(e.title)} in new window">↗</a></article>`;}
function render(){const list=filtered(),searching=!!$('#search').value||category!=='All';$('#edition').textContent=`EDITION 001 · ${catalog.length} EXPLAINERS${local.length?' · LOCAL ADDITIONS':''}`;$('#total').textContent=catalog.length;$('#filters').innerHTML=['All',...categories].map(c=>`<button data-filter="${esc(c)}" class="${c===category?'active':''}" aria-pressed="${c===category}">${esc(c)}<span>${c==='All'?catalog.length:catalog.filter(e=>e.category===c).length}</span></button>`).join('');$('#results').textContent=`${list.length} ${list.length===1?'essay':'essays'}${category!=='All'?' / '+category:''}`;$('#clearSearch').hidden=!$('#search').value;$('#empty').hidden=list.length>0;if($('#lead')) $('#lead').hidden=searching;$('#latestBlock').hidden=searching;
$('#grid').innerHTML=[...catalog].sort(newest).slice(0,3).map(card).join('');
let html='',cat,sub;for(const e of list){if(e.category!==cat){if(cat)html+='</div></section>';cat=e.category;sub=null;html+=`<section class="cat-group"><h3>${esc(cat)}<span>${list.filter(x=>x.category===cat).length}</span></h3>`;}if(e.subcategory!==sub){if(sub)html+='</div>';sub=e.subcategory;html+=`<div class="sub-group"><h4>${esc(sub)}</h4>`;}html+=row(e);}if(cat)html+='</div></section>';$('#catalog').innerHTML=html;}
const fileMap=Object.fromEntries(published.map(e=>[e.id,e.file]));
function link(id,standalone=false){if(standalone&&fileMap[id])return fileMap[id];let u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('id',id);if(standalone)u.searchParams.set('standalone','1');return u.href;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
async function copy(value,message){try{await navigator.clipboard.writeText(value);toast(message);}catch{const t=document.createElement('textarea');t.value=value;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?message:'Copy unavailable. Please copy the address from your browser.');}}
function share(id){copy(link(id),fileMap[id]?'Link copied. Pass the lightbulb on.':'Link copied — this local draft is only available in this browser.');}
const starter=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:18px/1.7 system-ui;max-width:700px;margin:50px auto;padding:24px;color:#203018;background:#f5f8ef}h1{line-height:1.1;font-size:42px}.model{padding:28px;background:#ddf3ae;border-radius:12px}input{width:100%}</style><h1>Start with a simple mechanism.</h1><p>Explain the everyday analogy, then show what actually changes.</p><div class="model"><label>Change the input: <output id="value">50</output><input type="range" value="50" oninput="document.getElementById('value').textContent=this.value"></label></div><h2>What to notice</h2><p>Describe the relationship your reader can see. State where the analogy breaks down.</p></html>`;
function frameHtml(e){return e.html+`<script>function report(){let d=document.documentElement;parent.postMessage({type:'eli5-progress',value:d.scrollHeight<=innerHeight?100:Math.min(100,Math.round(scrollY/(d.scrollHeight-innerHeight)*100))},'*')}addEventListener('scroll',report,{passive:true});addEventListener('load',report);addEventListener('keydown',e=>{if(!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&['Escape','ArrowLeft','ArrowRight'].includes(e.key))parent.postMessage({type:'eli5-key',key:e.key},'*')});new ResizeObserver(report).observe(document.documentElement);report();<\/script>`;}
function openReader(id,historyUpdate=true){const e=catalog.find(e=>e.id===id);if(!e){toast('This explainer is not in this browser’s catalog.');return;}active=e;lastFocus=document.activeElement;$('#readerTitle').textContent=e.title;if($('#readerCategory'))$('#readerCategory').textContent=(e.category||'Visual explainers').toUpperCase();$('#popout').href=fileMap[e.id]||link(e.id,true);$('#progress').style.width='0';if(fileMap[e.id]){$('#document').removeAttribute('srcdoc');$('#document').src=fileMap[e.id];}else{$('#document').removeAttribute('src');$('#document').srcdoc=frameHtml(e);}if(!$('#reader').open)$('#reader').showModal();if(historyUpdate){const u=new URL(location.href);u.searchParams.set('id',id);history.pushState({},'',u);} }
function closeReader(){if($('#reader').open)$('#reader').close();active=null;document.body.classList.remove('standalone');const u=new URL(location.href);u.search='';u.hash='';history.replaceState({},'',u);lastFocus?.focus();}
function navigate(delta){if(!active)return;const list=filtered().some(e=>e.id===active.id)?filtered():catalog;openReader(list[(list.findIndex(e=>e.id===active.id)+delta+list.length)%list.length].id);}
function reset(){category='All';$('#search').value='';$('#sort').value='newest';render();}
$('#search').addEventListener('input',render);$('#clearSearch').onclick=()=>{$('#search').value='';render();$('#search').focus();};$('#sort').onchange=render;$('#reset').onclick=reset;$('#home').onclick=e=>{e.preventDefault();reset();scrollTo({top:0,behavior:'smooth'});};document.addEventListener('click',e=>{let r=e.target.closest('[data-read]'),s=e.target.closest('[data-share]'),f=e.target.closest('[data-filter]');if(r)openReader(r.dataset.read);if(s)share(s.dataset.share);if(f){category=f.dataset.filter;render();if(f.closest('footer'))$('#catalogue').scrollIntoView({behavior:'smooth'});}});
try{if(localStorage.getItem('eli5-theme')==='light')document.body.classList.add('light');}catch{}$('#theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('eli5-theme',document.body.classList.contains('light')?'light':'dark');}catch{}if(active&&!fileMap[active.id])$('#document').srcdoc=frameHtml(active);$('#theme').setAttribute('aria-label',document.body.classList.contains('light')?'Toggle dark mode':'Toggle light mode');};
$('#closeReader').onclick=closeReader;$('#reader').addEventListener('cancel',e=>{e.preventDefault();closeReader();});$('#reader').onclick=e=>{if(e.target===$('#reader')){const r=$('#reader').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeReader();}};$('#prev').onclick=()=>navigate(-1);$('#next').onclick=()=>navigate(1);if($('#readerShare')) $('#readerShare').onclick=()=>active&&share(active.id);
$('#draftCategory').innerHTML=categories.map(c=>`<option>${c}</option>`).join('');$('#footerCategories').innerHTML=categories.map(c=>`<button data-filter="${c}">${c}</button>`).join('');$('#draftHtml').value=starter;$('#openStudio').onclick=()=>{$('#preview').srcdoc=$('#draftHtml').value;$('#studio').showModal();};$('#closeStudio').onclick=()=>$('#studio').close();$('#studio').addEventListener('click',e=>{if(e.target===$('#studio')){let r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});let previewTimer;$('#draftHtml').oninput=()=>{clearTimeout(previewTimer);previewTimer=setTimeout(()=>$('#preview').srcdoc=$('#draftHtml').value,220);};$('#template').onclick=()=>copy(starter,'Starter template copied.');$('#studioForm').onsubmit=e=>{e.preventDefault();const title=$('#draftTitle').value.trim(),summary=$('#draftSummary').value.trim(),html=$('#draftHtml').value.trim();if(!title||!summary||!html){$('#studioError').textContent='Please complete every field.';return;}const item={id:'local-'+crypto.randomUUID(),title,summary,html,category:$('#draftCategory').value,minutes:Math.max(1,Math.ceil(html.replace(/<[^>]*>/g,' ').split(/\s+/).length/200)),bullets:[summary,'Your own interactive visual explainer'],tags:['local','draft'],date:new Date().toISOString().slice(0,10),subcategory:'Your drafts',color:'#ff8059',nodes:['IDEA','MODEL','INSIGHT']};try{localStorage.setItem('eli5-drafts',JSON.stringify([...local,item]));}catch{$('#studioError').textContent='Browser storage is full or unavailable. Your draft is still here; copy it before closing.';return;}local.push(item);catalog.push(item);reset();$('#studio').close();$('#studioForm').reset();$('#draftHtml').value=starter;$('#studioError').textContent='';toast('Explainer added to your local index.');};
function key(e){const typing=/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||'');if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'||e.key==='/'&&!typing&&!$('#reader').open&&!$('#studio').open){e.preventDefault();if(!$('#reader').open&&!$('#studio').open)$('#search').focus();}if($('#reader').open&&!typing){if(e.key==='ArrowLeft')navigate(-1);if(e.key==='ArrowRight')navigate(1);if(e.key==='Escape'){e.preventDefault();closeReader();}}}document.addEventListener('keydown',key);window.addEventListener('message',e=>{if(e.source!==$('#document').contentWindow)return;if(e.data?.type==='eli5-progress'&&Number.isFinite(e.data.value))$('#progress').style.width=Math.max(0,Math.min(100,e.data.value))+'%';if(e.data?.type==='eli5-key')key({key:e.data.key,preventDefault(){}});if(e.data?.type==='eli5-close')closeReader();});window.addEventListener('popstate',()=>{let id=new URL(location.href).searchParams.get('id');if(id)openReader(id,false);else{active=null;$('#reader').close();}});render();const params=new URL(location.href).searchParams;if(params.get('id')){if(params.get('standalone'))document.body.classList.add('standalone');openReader(params.get('id'),false);if(!active)document.body.classList.remove('standalone');}
