'use strict';
const $=s=>document.querySelector(s),categories=['AI & Frontier','Monetary Architecture','Macroeconomics','Energy & Physics','Infrastructure','Distributed Systems'];
const base=[
['money-india','How money actually works in India','Monetary Architecture',12,'Follow the balance sheets, not the banknotes.',['A loan creates a matching bank deposit','Payments move claims between balance sheets'],'money','#ff8059',['RBI','BANKS','YOU']],
['ai-alignment','The alignment problem, without the sci-fi','AI & Frontier',7,'When getting exactly what you asked for is the problem.',['Objectives are proxies for what we value','Capability and reliability are different axes'],'ai','#c3b8ff',['INTENT','OBJECTIVE','BEHAVIOR']],
['fluid-flow','Why fast-moving fluids lose pressure','Energy & Physics',6,'A narrow pipe. A faster flow. A surprising trade-off.',['Continuity links cross-section and speed','Bernoulli tracks an ideal flow’s energy budget'],'fluid','#8fc9fb',['WIDE','NARROW','WIDE']],
['inflation','Inflation is a story of competing flows','Macroeconomics',8,'More money is only one part of the price puzzle.',['Demand can outrun productive capacity','Supply shocks can raise prices without a boom'],'inflation','#ffb889',['DEMAND','CAPACITY','PRICES']],
['battery','Inside a lithium-ion battery','Energy & Physics',5,'Two paths, one circuit, and a chemical desire to move.',['Ions cross the electrolyte; electrons take the wire','Charging reverses the discharge reaction'],'battery','#ff8059',['ANODE','LOAD','CATHODE']],
['chip-chain','A chip’s very long journey home','Infrastructure',9,'The global relay behind a few square millimetres of silicon.',['Different stages create different bottlenecks','Capacity is more than the number of factories'],'supply','#f5cb70',['DESIGN','FAB','PACKAGE'],['Follow the handoffs|A chip moves from architecture and circuit design to wafer fabrication, testing, packaging, and integration into a product. Materials, equipment, software, and specialist services support each stage. A finished chip is the output of a network.','Why a missing part matters|A highly specialized tool or chemical can constrain an entire production line. Building another factory is not enough if the equipment, trained staff, qualified inputs, or customer approvals are missing.','Time is part of capacity|Manufacturing has long lead times and yield losses. Yield is the share of output that passes requirements. A line with impressive nominal throughput may produce far fewer usable chips while a process matures.','The model to keep|Trace a product through stages, then ask what each stage must receive before it can proceed. Resilience comes from understanding dependencies, substitution limits, inventories, and recovery times.']],
['consensus','How computers agree without a boss','Distributed Systems',8,'One shared history, many imperfect messengers.',['Quorums make conflicting decisions intersect','Agreement has assumptions and trade-offs'],'consensus','#90d6bd',['NODE A','NODE B','NODE C'],['Messages do not arrive together|Imagine three machines maintaining one shared record. A network delay can make one look dead when it is merely slow. Machines cannot treat the absence of a message as perfect proof of failure.','Overlapping majorities|In a group of three, any two-machine majority overlaps every other majority. Consensus protocols use overlap with rules for terms, voting, and logs to protect decisions. A majority alone, without those rules, does not define a safe protocol.','Progress versus protection|During a network split, a system may stop accepting writes in the minority partition to avoid conflicting histories. Safety means forbidden conflicting outcomes do not occur; liveness means the system eventually makes progress under its stated assumptions.','The model to keep|Ask what failure model is assumed, who can vote, and when a value becomes committed. Crash-tolerant consensus is not automatically safe against participants that lie.']],
['repo','Repo markets: the overnight engine room','Monetary Architecture',6,'A short-term loan wearing the clothes of a securities trade.',['Collateral supports short-term funding','A haircut is a buffer, not a guarantee'],'money','#ff8059',['CASH','COLLATERAL','REPAY']],
['transformers','Attention is a routing system','AI & Frontier',10,'How a transformer decides which context to bring forward.',['Attention forms context-dependent weighted mixtures','Prediction is not a guarantee of truth'],'ai','#c3b8ff',['QUERY','KEYS','VALUES']],
['grid','Why the power grid needs balance','Infrastructure',7,'Electricity is a live coordination problem.',['Supply and demand must balance in real time','Frequency helps reveal an imbalance'],'grid','#8fc9fb',['GENERATE','GRID','DEMAND']]
].map((r,i)=>({id:r[0],title:r[1],category:r[2],minutes:r[3],summary:r[4],bullets:r[5],kind:r[6],color:r[7],nodes:r[8],sections:r[9],tags:[r[6],...r[8]],index:i+1}));
let local=[];try{local=JSON.parse(localStorage.getItem('eli5-drafts')||'[]').filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.html==='string'&&categories.includes(x.category));}catch{}let catalog=[...base,...local],category='All',active=null,lastFocus=null,toastTimer;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function diagram(e){const c=e.color||'#ff8059',n=e.nodes||['IDEA','MODEL','INSIGHT'];let inner='';if(e.kind==='fluid'){inner=`<path d="M20 36H90L135 58H195L240 36H300M20 118H90L135 96H195L240 118H300" fill="none" stroke="${c}" stroke-width="2"/><path d="M20 58Q110 56 140 72H194Q225 58 300 58M20 78H300M20 97Q110 99 140 84H194Q225 99 300 97" fill="none" stroke="${c}" opacity=".4"/><text x="60" y="25">LOW SPEED</text><text x="164" y="132">HIGHER SPEED · LOWER PRESSURE</text><path d="M151 77h30m-6-5 6 5-6 5" fill="none" stroke="${c}"/>`;}else if(e.kind==='ai'){inner=Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>`<path d="M67 ${42+i*34}L155 ${42+j*34}M165 ${42+i*34}L253 ${42+j*34}" stroke="${c}" opacity="${i===j?.65:.17}"/>`).join('')).join('')+[57,160,263].map(x=>[42,76,110].map(y=>`<circle cx="${x}" cy="${y}" r="7" fill="#23281e" stroke="${c}"/>`).join('')).join('');}else if(e.kind==='inflation'){inner=`<path d="M46 20V120H290" fill="none" stroke="#69715f"/><path d="M55 109C120 100 140 78 180 54S230 32 285 23M55 34C120 45 170 68 285 106" fill="none" stroke="${c}" stroke-width="2"/><circle cx="167" cy="69" r="5" fill="${c}"/><path d="M167 69V120M46 69H167" stroke="${c}" stroke-dasharray="3 4" opacity=".4"/><text x="185" y="141">QUANTITY →</text>`;}else{inner=n.map((x,i)=>`<rect x="${19+i*103}" y="50" width="76" height="51" rx="5" fill="#20271b" stroke="${c}" stroke-opacity=".7"/><text x="${57+i*103}" y="79" fill="${c}">${esc(x)}</text>`).join('')+`<path d="M96 75h25m-5-4 5 4-5 4M199 75h25m-5-4 5 4-5 4" stroke="${c}" fill="none"/><path d="M263 105v18H57v-18" stroke="${c}" stroke-dasharray="3 4" opacity=".4" fill="none"/>`; }return `<svg viewBox="0 0 320 155" role="img" aria-label="${esc(e.title)} schematic"><style>text{font:8px monospace;text-anchor:middle;fill:${c}}</style>${inner}</svg>`;}
function filtered(){let q=$('#search').value.trim().toLowerCase();let list=catalog.filter(e=>(category==='All'||e.category===category)&&[e.title,e.category,e.summary,...(e.tags||[])].join(' ').toLowerCase().includes(q));switch($('#sort').value){case'short':list.sort((a,b)=>a.minutes-b.minutes);break;case'long':list.sort((a,b)=>b.minutes-a.minutes);break;case'alpha':list.sort((a,b)=>a.title.localeCompare(b.title));}return list;}
function render(){const list=filtered();$('#edition').textContent=`EDITION 001 · ${catalog.length} EXPLAINERS${local.length?' · LOCAL ADDITIONS':''}`;$('#total').textContent=catalog.length;$('#filters').innerHTML=['All',...categories].map(c=>`<button data-filter="${esc(c)}" class="${c===category?'active':''}" aria-pressed="${c===category}">${esc(c)}<span>${c==='All'?catalog.length:catalog.filter(e=>e.category===c).length}</span></button>`).join('');$('#results').textContent=`${list.length} ${list.length===1?'essay':'essays'}${category!=='All'?' / '+category:''}`;$('#clearSearch').hidden=!$('#search').value;$('#empty').hidden=list.length>0;if($('#lead')) $('#lead').hidden=!!$('#search').value||category!=='All';$('#grid').innerHTML=list.map(e=>`<article class="card" style="--card-color:${e.color||'#ff8059'}"><div class="card-top"><div class="card-meta"><span class="index">${String(catalog.indexOf(e)+1).padStart(2,'0')}</span><span>${esc(e.category.toUpperCase())}</span><span class="time">${e.minutes} MIN ↗</span></div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="diagram">${diagram(e)}</div></div><ul>${e.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><div class="card-actions"><button data-read="${esc(e.id)}">Read essay <span>↗</span></button><button class="icon" data-share="${esc(e.id)}" aria-label="Copy share link for ${esc(e.title)}">⧉</button><a class="icon" href="${link(e.id,true)}" target="_blank" rel="noopener" aria-label="Open ${esc(e.title)} in new window">↗</a></div></article>`).join('');}
const fileMap = {
  'money-india': 'how-money-actually-works-in-india.html',
  'ai-alignment': 'openai-hugging-face-incident.html',
  'fluid-flow': 'openai-navier-stokes-claim-and-critique-eli5.html',
  'inflation': 'eli5-india-gdp-78.html',
  'battery': 'eli5-lithium-ion-battery.html',
  'transformers': 'the-transformer-industrys-hidden-bkt-eli5.html',
  'repo': 'fcnr-b-swap-for-school-kids-eli5.html',
  'grid': 'explainers/power-grid-balance-eli5.html'
};
function link(id,standalone=false){if(standalone&&fileMap[id])return fileMap[id];let u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('id',id);if(standalone)u.searchParams.set('standalone','1');return u.href;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
async function copy(value,message){try{await navigator.clipboard.writeText(value);toast(message);}catch{const t=document.createElement('textarea');t.value=value;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?message:'Copy unavailable. Please copy the address from your browser.');}}
function share(id){copy(link(id),base.some(e=>e.id===id)?'Link copied. Pass the lightbulb on.':'Link copied — this local draft is only available in this browser.');}
const starter=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:18px/1.7 system-ui;max-width:700px;margin:50px auto;padding:24px;color:#203018;background:#f5f8ef}h1{line-height:1.1;font-size:42px}.model{padding:28px;background:#ddf3ae;border-radius:12px}input{width:100%}</style><h1>Start with a simple mechanism.</h1><p>Explain the everyday analogy, then show what actually changes.</p><div class="model"><label>Change the input: <output id="value">50</output><input type="range" value="50" oninput="document.getElementById('value').textContent=this.value"></label></div><h2>What to notice</h2><p>Describe the relationship your reader can see. State where the analogy breaks down.</p></html>`;
function essayHtml(e){if(e.html)return e.html;return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>@font-face{font-family:Outfit;src:url("${new URL('assets/outfit.ttf',location.href).href}")}html,body{scrollbar-width:none}html::-webkit-scrollbar,body::-webkit-scrollbar{display:none;width:0;height:0}body{margin:0;background:${document.body.classList.contains('light')?'#f3f2ee':'#161616'};color:${document.body.classList.contains('light')?'#242424':'#f3f1ec'};font:18px/1.85 Outfit,system-ui}main{max-width:750px;margin:0 auto;padding:55px 28px 90px}h1{font-size:clamp(32px,6vw,53px);letter-spacing:-2px;line-height:1.12}h2{font-size:26px;line-height:1.3;margin-top:40px}p{opacity:.8}small{font:12px monospace;letter-spacing:1px;color:#cb633f}.deck{font-size:22px}figure{margin:30px 0;background:#211f1e;border:1px solid #455134;border-radius:12px;padding:20px}svg{height:190px;width:100%}.model{padding:25px;background:#282423;border:1px solid #67574f;border-radius:12px;color:#f5ece7}.model p{font-size:15px;margin:8px 0}input{width:100%;accent-color:#ff8059}output{font-weight:700;color:#ff8059}.note{font-size:14px;border-top:1px solid #526042;margin-top:35px;padding-top:22px}li{margin:10px 0}</style></head><body><main><small>${esc(e.category.toUpperCase())} / ${e.minutes} MIN READ</small><h1>${esc(e.title)}</h1><p class="deck">${esc(e.summary)}</p><figure>${diagram(e)}</figure>${e.sections.map((s,i)=>{const [h,p]=s.split('|');return `<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>${i===1?`<div class="model"><strong>Try the mental model</strong><p>Move through the mechanism. Each stage depends on the one before it.</p><label>Step: <output id="v">1 / 3</output><input aria-label="${money?'Loan amount':'Mechanism step'}" id="range" type="range" min="1" max="3" step="1" value="1"></label><p id="result">${esc(e.nodes[0])}: start here and follow the diagram.</p></div>`:''}`}).join('')}<h2>The two ideas to take with you</h2><ul>${e.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="note">A simplified educational model. Real systems add institutional rules, frictions, and exceptions. Start with the mechanism, then examine its assumptions.</p></main><script>document.getElementById('range').oninput=function(){let n=Number(this.value);document.getElementById('v').textContent=n+' / 3';document.getElementById('result').textContent=${JSON.stringify(e.nodes)}[n-1]+': '+${JSON.stringify(e.bullets.concat('The full mechanism connects these stages.'))}[n-1];};<\/script></body></html>`;}
function frameHtml(e){return essayHtml(e)+`<script>function report(){let d=document.documentElement;parent.postMessage({type:'eli5-progress',value:d.scrollHeight<=innerHeight?100:Math.min(100,Math.round(scrollY/(d.scrollHeight-innerHeight)*100))},'*')}addEventListener('scroll',report,{passive:true});addEventListener('load',report);addEventListener('keydown',e=>{if(!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&['Escape','ArrowLeft','ArrowRight'].includes(e.key))parent.postMessage({type:'eli5-key',key:e.key},'*')});new ResizeObserver(report).observe(document.documentElement);report();<\/script>`;}
function openReader(id,historyUpdate=true){const e=catalog.find(e=>e.id===id);if(!e){toast('This explainer is not in this browser’s catalog.');return;}active=e;lastFocus=document.activeElement;$('#readerTitle').textContent=e.title;if($('#readerCategory'))$('#readerCategory').textContent=(e.category||'Visual explainers').toUpperCase();$('#popout').href=fileMap[e.id]||link(e.id,true);$('#progress').style.width='0';if(fileMap[e.id]){$('#document').removeAttribute('srcdoc');$('#document').src=fileMap[e.id];}else{$('#document').removeAttribute('src');$('#document').srcdoc=frameHtml(e);}if(!$('#reader').open)$('#reader').showModal();if(historyUpdate){const u=new URL(location.href);u.searchParams.set('id',id);history.pushState({},'',u);} }
function closeReader(){if($('#reader').open)$('#reader').close();active=null;document.body.classList.remove('standalone');const u=new URL(location.href);u.search='';u.hash='';history.replaceState({},'',u);lastFocus?.focus();}
function navigate(delta){if(!active)return;const list=filtered().some(e=>e.id===active.id)?filtered():catalog;openReader(list[(list.findIndex(e=>e.id===active.id)+delta+list.length)%list.length].id);}
function reset(){category='All';$('#search').value='';$('#sort').value='featured';render();}
$('#search').addEventListener('input',render);$('#clearSearch').onclick=()=>{$('#search').value='';render();$('#search').focus();};$('#sort').onchange=render;$('#reset').onclick=reset;$('#home').onclick=e=>{e.preventDefault();reset();scrollTo({top:0,behavior:'smooth'});};document.addEventListener('click',e=>{let r=e.target.closest('[data-read]'),s=e.target.closest('[data-share]'),f=e.target.closest('[data-filter]');if(r)openReader(r.dataset.read);if(s)share(s.dataset.share);if(f){category=f.dataset.filter;render();if(f.closest('footer'))$('.collection').scrollIntoView({behavior:'smooth'});}});
try{if(localStorage.getItem('eli5-theme')==='light')document.body.classList.add('light');}catch{}$('#theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('eli5-theme',document.body.classList.contains('light')?'light':'dark');}catch{}if(active&&!fileMap[active.id])$('#document').srcdoc=frameHtml(active);$('#theme').setAttribute('aria-label',document.body.classList.contains('light')?'Toggle dark mode':'Toggle light mode');};
$('#closeReader').onclick=closeReader;$('#reader').addEventListener('cancel',e=>{e.preventDefault();closeReader();});$('#reader').onclick=e=>{if(e.target===$('#reader')){const r=$('#reader').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeReader();}};$('#prev').onclick=()=>navigate(-1);$('#next').onclick=()=>navigate(1);if($('#readerShare')) $('#readerShare').onclick=()=>active&&share(active.id);
$('#draftCategory').innerHTML=categories.map(c=>`<option>${c}</option>`).join('');$('#footerCategories').innerHTML=categories.map(c=>`<button data-filter="${c}">${c}</button>`).join('');$('#draftHtml').value=starter;$('#openStudio').onclick=()=>{$('#preview').srcdoc=$('#draftHtml').value;$('#studio').showModal();};$('#closeStudio').onclick=()=>$('#studio').close();$('#studio').addEventListener('click',e=>{if(e.target===$('#studio')){let r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});let previewTimer;$('#draftHtml').oninput=()=>{clearTimeout(previewTimer);previewTimer=setTimeout(()=>$('#preview').srcdoc=$('#draftHtml').value,220);};$('#template').onclick=()=>copy(starter,'Starter template copied.');$('#studioForm').onsubmit=e=>{e.preventDefault();const title=$('#draftTitle').value.trim(),summary=$('#draftSummary').value.trim(),html=$('#draftHtml').value.trim();if(!title||!summary||!html){$('#studioError').textContent='Please complete every field.';return;}const item={id:'local-'+crypto.randomUUID(),title,summary,html,category:$('#draftCategory').value,minutes:Math.max(1,Math.ceil(html.replace(/<[^>]*>/g,' ').split(/\s+/).length/200)),bullets:[summary,'Your own interactive visual explainer'],tags:['local','draft'],color:'#ff8059',nodes:['IDEA','MODEL','INSIGHT']};try{localStorage.setItem('eli5-drafts',JSON.stringify([...local,item]));}catch{$('#studioError').textContent='Browser storage is full or unavailable. Your draft is still here; copy it before closing.';return;}local.push(item);catalog.push(item);reset();$('#studio').close();$('#studioForm').reset();$('#draftHtml').value=starter;$('#studioError').textContent='';toast('Explainer added to your local index.');};
function key(e){const typing=/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||'');if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'||e.key==='/'&&!typing&&!$('#reader').open&&!$('#studio').open){e.preventDefault();if(!$('#reader').open&&!$('#studio').open)$('#search').focus();}if($('#reader').open&&!typing){if(e.key==='ArrowLeft')navigate(-1);if(e.key==='ArrowRight')navigate(1);if(e.key==='Escape'){e.preventDefault();closeReader();}}}document.addEventListener('keydown',key);window.addEventListener('message',e=>{if(e.source!==$('#document').contentWindow)return;if(e.data?.type==='eli5-progress'&&Number.isFinite(e.data.value))$('#progress').style.width=Math.max(0,Math.min(100,e.data.value))+'%';if(e.data?.type==='eli5-key')key({key:e.data.key,preventDefault(){}});if(e.data?.type==='eli5-close')closeReader();});window.addEventListener('popstate',()=>{let id=new URL(location.href).searchParams.get('id');if(id)openReader(id,false);else{active=null;$('#reader').close();}});render();const params=new URL(location.href).searchParams;if(params.get('id')){if(params.get('standalone'))document.body.classList.add('standalone');openReader(params.get('id'),false);if(!active)document.body.classList.remove('standalone');}
